### ISSUE TITLE
flag inconsistency in bcftools prune function

### ISSUE THREAD

**Issue by waterfleas** [jessstapley/Physalia_AdaptationGenomics#1]
Hello, 
The flags have changed for bcftools +prune leaving your code broken.

flag -l   has changed to (?) -m
so your advised one-liner 
bcftools +prune -l 0.2  -w 5000 file.vcf -Ov -o file_pruned.vcf
should be
bcftools +prune -m 0.2  -w 5000 file.vcf -Ov -o file_pruned.vcf

**Comment by jessstapley** [comment]
Thanks Waterfleas for letting me know and providing the updated code
